In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

print(a.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
b=np.array([[1],[2],[3],[4]])
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [5]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
5


In [18]:
a=np.zeros((3,3))
print(a)

b=np.ones((3,3))
print(b)
#constant array
c=np.full((3,2),5)
print(c)

#identity Matrix
d=np.eye(4)
print(d)


#random Matrix
randomMatrix=np.random.random((2,3))
print(randomMatrix)
print()
print(randomMatrix[:,1])

randomMatrix[1,1:3]=1
print(randomMatrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.51638552 0.01419859 0.19311379]
 [0.2458635  0.51214017 0.62108705]]

[0.01419859 0.51214017]
[[0.51638552 0.01419859 0.19311379]
 [0.2458635  1.         1.        ]]


In [26]:
#set some rows and columns with any values
z=np.zeros((3,3))
print(z)
z[1,:]=5
z[:,-1]=7
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


In [27]:
#data types
print(z.dtype)
z=np.zeros((3,3),dtype=np.int64)
print(z.dtype)


float64
int64


In [32]:
# Matematical Operations
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

# Elementwies Additions
print(x+y)
print(np.add(x,y))
print(x-y)
print(np.subtract(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [35]:
print(x*y)
print(np.multiply(x,y))
print(x/y)
print(np.divide(x,y))
print(np.sqrt(x))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [37]:
#Matrix Multiplication and dot Products

print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [39]:
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [56]:
# multiplication of vectors

a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a.dot(b))

30


In [52]:
print(a)
print(sum(a))

[1 2 3 4]
10


In [53]:
print(x)
print(np.sum(x))
#axis=0 along column
# axis=1 along row
print(np.sum(x,axis=1))


[[1 2]
 [3 4]]
10
[3 7]


In [59]:
#stacking of arrays
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a)
b=b**2;
print(b)
print(np.stack((a,b),axis=1))

print()
#reshape a numpy array
a=np.stack((a,b),axis=0);
print(a)
a=a.reshape(4,2)
print(a)

[1 2 3 4]
[ 1  4  9 16]
[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]

[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


# Numpy Random Module

In [63]:
a=np.arange(10)
print(a)
b=np.arange(10)+5
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [82]:
np.random.shuffle(a)
print(a)
# randomly pick one element form ararray
element=np.random.choice(a)
print(element)
print(np.where(a==element)[0][0])

[5 6 8]
8
2


In [83]:
a=np.random.rand(2,3) # here 2,3 are size of array
print(a)

a=np.random.randn(2,3)
print(a)

a=np.random.randint(5,10,3) # range [5,10] 3 nos



[[0.09728073 0.53189142 0.16416581]
 [0.0108051  0.26807334 0.28653355]]
[[1.39039108 1.01019027 0.13575679]
 [2.78724699 1.27878952 2.11781018]]


## STatistic Calculation