In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [49]:
df=pd.read_csv('./Training Data/Diabetes_XTrain.csv');
XTrain=df.values;
print(XTrain.shape);
df.head()

(576, 8)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            7      168             88             42      321  38.2   
1            8      110             76              0        0  27.8   
2            7      147             76              0        0  39.4   
3            2      100             66             20       90  32.9   
4            4      129             86             20      270  35.1   

   DiabetesPedigreeFunction  Age  
0                     0.787   40  
1                     0.237   58  
2                     0.257   43  
3                     0.867   28  
4                     0.231   23

In [50]:
df=pd.read_csv('./Training Data/Diabetes_YTrain.csv');
YTrain=df.values;
print(YTrain.shape);
df.head()

(576, 1)


Outcome
0        1
1        0
2        1
3        1
4        0

In [51]:
#scalling of Train data
# scalling is important without scalling accuracy is 50 after scalling 76%
# after increasing value of k to 25 accuracy reach 79%
u=np.mean(XTrain,axis=0);
sigma=np.std(XTrain,axis=0);

XTrain=(XTrain-u)/sigma;

In [52]:
## now  apply knn 

def distance(x1,x2):
    return np.sqrt(sum((x2-x1)**2));

def Knn(X,y,query_Point,k=25):
    vals=[];
    for i in range(X.shape[0]):
        dis=distance(X[i],query_Point);
        vals.append((dis,y[i]));
    
    vals=sorted(vals);
    vals=vals[:k];
    vals=np.array(vals);
    
    freq=np.unique(vals[:,1],return_counts=True);
    
    indx=np.argmax(freq[1]);
    
    return freq[0][indx];
    

In [53]:
XTest=pd.read_csv("Diabetes_Xtest.csv").values;
#scalling of test data
u=np.mean(XTest,axis=0);
sigma=np.std(XTest,axis=0);

XTest=(XTest-u)/sigma;

YTest=[];

for i in range(XTest.shape[0]):
    pred=Knn(XTrain,YTrain,XTest[i]);
    YTest.append(pred);

In [54]:
YTest=np.array(YTest);
df=pd.DataFrame(YTest,columns=["Outcome"]);
df.to_csv("output.csv",index=False);

In [30]:
pd.DataFrame?

In [20]:
arr=[[1,2,3,4],[5,6,7,8],[9,10,11,12]];
arr=np.array(arr);
print(arr);

u=np.mean(arr,axis=0);
print(u);

sigma=np.std(arr,axis=0);
print(sigma);


arr=arr-u;
print(arr);

arr=(arr)/sigma;
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5. 6. 7. 8.]
[3.26598632 3.26598632 3.26598632 3.26598632]
[[-4. -4. -4. -4.]
 [ 0.  0.  0.  0.]
 [ 4.  4.  4.  4.]]
[[-1.22474487 -1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487  1.22474487]]
